version: "3.8"

volumes:
  prometheus_data: {}
  grafana_data: {}

networks:
  monitoring_net:
    driver: bridge

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: part03_ex04_prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"
      - "--web.enable-lifecycle"
    ports:
      - "9090:9090"
    networks:
      - monitoring_net
    restart: always

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: part03_ex04_grafana
    ports:
      - "8080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    privileged: true
    depends_on:
      - prometheus
    networks:
      - monitoring_net
    restart: always

  grafana:
    image: grafana/grafana:latest
    container_name: part03_ex04_grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
    depends_on:
      - prometheus
    networks:
      - monitoring_net
    restart: always
