version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/Part02_Ex13_React_Nginx/react-app/"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
      - "npm"
      - "react-app"
    commit-message:
      prefix: "chore(deps)"
      prefix-development: "chore(dev-deps)"
      include: "scope"
    open-pull-requests-limit: 5
    reviewers:
      - "dhlananhh"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "ci"
      - "github-actions"
    commit-message:
      prefix: "chore(ci)"
      include: "scope"
    open-pull-requests-limit: 3
    reviewers:
      - "dhlananhh"
