version: "3.8"
services:
  flask-app-1:
    build:
      context: .
      dockerfile: Dockerfile.flask
    container_name: bt3_flask_1
    expose:
      - "5000"
    networks:
      - flask-net
    restart: always
  flask-app-2:
    build:
      context: .
      dockerfile: Dockerfile.flask
    container_name: bt3_flask_2
    expose:
      - "5000"
    networks:
      - flask-net
    restart: always
  nginx:
    image: nginx:alpine
    container_name: bt3_nginx_lb
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - flask-net
    depends_on:
      - flask-app-1
      - flask-app-2
    restart: always
networks:
  flask-net:
    driver: bridge
