version: "3.8"

networks:
  mynetwork:
    driver: bridge

services:
  react-app:
    build: ./react-app
    container_name: react-app-container
    ports:
      - "8081:80"
    environment:
      REACT_DOCKER_PORT: 80
      REACT_APP_API_BASE_URL: http://localhost:8081/api
    networks:
      - mynetwork
  node-app:
    build: ./node-app
    container_name: nodejs-app-container
    ports:
      - "8080:8080"
    environment:
      NODE_DOCKER_PORT: 8080
    networks:
      - mynetwork