version: "3.8"

services:
  mysql_db:
    image: mysql:8.0
    container_name: simple_mysql_container
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: verysecretrootpassword
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3307"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
