version: '3.8'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: your_strong_root_password
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password

  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - "8081:80"      
    environment:
      PMA_HOST: db      
      PMA_PORT: 3306    
    depends_on:        
      - db