version: "3.8"
services:
  mongodb:
    image: mongo:latest
    container_name: my_mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: rootadmin
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
  mongo-express:
    image: mongo-express:latest
    container_name: my_mongo_express
    restart: unless-stopped
    ports:
      - "8082:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
      ME_CONFIG_MONGODB_ADMINUSERNAME: rootadmin
      ME_CONFIG_MONGODB_ADMINPASSWORD: rootpassword
      ME_CONFIG_BASICAUTH_USERNAME: adminuser
      ME_CONFIG_BASICAUTH_PASSWORD: adminpassword
    depends_on:
      - mongodb
volumes:
  mongo_data:
