version: '3.8'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: verysecretrootpassword
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306" 
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always

volumes:
  mysql_data: 
    driver: local 
    name: my_custom_mysql_volume_name 