version: "3.8"
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: basic_wordpress_db
      MYSQL_USER: wp_user
      MYSQL_PASSWORD: wp_password
      MYSQL_ROOT_PASSWORD: root_password_!
    volumes:
      - db_data:/var/lib/mysql
  wordpress:
    image: wordpress:latest
    restart: always
    ports:
      - "8001:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: basic_wordpress_db
      WORDPRESS_DB_USER: wp_user
      WORDPRESS_DB_PASSWORD: wp_password
    depends_on:
      - db
    volumes:
      - wp_content:/var/www/html
volumes:
  db_data:
  wp_content:
