version: '3.8'

services:
  db:
    image: mysql:5.7 
    volumes:
      - db_data:/var/lib/mysql 
    environment:
      MYSQL_ROOT_PASSWORD: your_strong_root_password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress_user
      MYSQL_PASSWORD: wordpress_password
    restart: always 

  wordpress:
    image: wordpress:latest
    volumes:
      - wp_files:/var/www/html 
    ports:
      - "8000:80"  
    environment:
      WORDPRESS_DB_HOST: db:3306 
      WORDPRESS_DB_USER: wordpress_user
      WORDPRESS_DB_PASSWORD: wordpress_password
      WORDPRESS_DB_NAME: wordpress
    depends_on:
      - db         
    restart: always

volumes: 
  db_data:
  wp_files: