version: "3.9"

services:
  app:
    build: ./app
    volumes:
      - ./app:/app
    ports:
      - "5000:5000"
    networks:
      - cicd-network

  tests:
    build:
      context: ./app
      dockerfile: Dockerfile.test
    volumes:
      - ./app:/app
    entrypoint: ["pytest", "/app/test_app.py"]
    depends_on:
      - app
    networks:
      - cicd-network
volumes:
  app-data:
networks:
  cicd-network:
    driver: bridge
