version: "3.9"

services:
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - app
    networks:
      - cicd-network

  app:
    image: app-image
    networks:
      - cicd-network
networks:
  cicd-network:
    driver: bridge
